"""
NetAutomate Pro - Backup Manager
Handles configuration backup and restoration.

Author: Navaneethraj KA
"""

import os
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict

from .utils import setup_logging

logger = setup_logging()


class BackupManager:
    """
    Manages device configuration backups.
    Supports versioning, compression, and restoration.
    """
    
    def __init__(self, backup_dir: str = "backups"):
        """
        Initialize the backup manager.
        
        Args:
            backup_dir: Directory to store backups
        """
        self.backup_dir = Path(backup_dir)
        self.backup_dir.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"BackupManager initialized. Backup directory: {self.backup_dir}")
    
    def save_backup(self, hostname: str, config: str, 
                    suffix: str = "") -> str:
        """
        Save a configuration backup.
        
        Args:
            hostname: Device hostname
            config: Configuration content
            suffix: Optional suffix for the filename
            
        Returns:
            Path to the saved backup file
        """
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        if suffix:
            filename = f"{hostname}_{timestamp}_{suffix}.cfg"
        else:
            filename = f"{hostname}_{timestamp}.cfg"
        
        filepath = self.backup_dir / filename
        
        # Add header with metadata
        header = f"""!
! Configuration backup for {hostname}
! Backup date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
! Generated by NetAutomate Pro
!
"""
        
        with open(filepath, 'w') as f:
            f.write(header)
            f.write(config)
        
        logger.info(f"Backup saved: {filepath}")
        return str(filepath)
    
    def get_latest_backup(self, hostname: str) -> Optional[str]:
        """
        Get the most recent backup for a device.
        
        Args:
            hostname: Device hostname
            
        Returns:
            Path to the latest backup file or None
        """
        pattern = f"{hostname}_*.cfg"
        backups = sorted(self.backup_dir.glob(pattern), reverse=True)
        
        if backups:
            return str(backups[0])
        return None
    
    def list_backups(self, hostname: str = None) -> List[Dict]:
        """
        List all backups, optionally filtered by hostname.
        
        Args:
            hostname: Optional hostname filter
            
        Returns:
            List of backup information dictionaries
        """
        if hostname:
            pattern = f"{hostname}_*.cfg"
        else:
            pattern = "*.cfg"
        
        backups = []
        for backup_file in sorted(self.backup_dir.glob(pattern), reverse=True):
            stat = backup_file.stat()
            backups.append({
                'filename': backup_file.name,
                'path': str(backup_file),
                'size': stat.st_size,
                'modified': datetime.fromtimestamp(stat.st_mtime).isoformat(),
                'hostname': backup_file.name.split('_')[0]
            })
        
        return backups
    
    def get_backup_content(self, backup_path: str) -> str:
        """
        Read the content of a backup file.
        
        Args:
            backup_path: Path to backup file
            
        Returns:
            Backup file content
        """
        with open(backup_path, 'r') as f:
            return f.read()
    
    def compare_backups(self, backup1: str, backup2: str) -> Dict:
        """
        Compare two backup files.
        
        Args:
            backup1: Path to first backup
            backup2: Path to second backup
            
        Returns:
            Dictionary with comparison results
        """
        content1 = self.get_backup_content(backup1).split('\n')
        content2 = self.get_backup_content(backup2).split('\n')
        
        # Filter out comments and empty lines
        lines1 = set(l.strip() for l in content1 if l.strip() and not l.startswith('!'))
        lines2 = set(l.strip() for l in content2 if l.strip() and not l.startswith('!'))
        
        added = lines2 - lines1
        removed = lines1 - lines2
        unchanged = lines1 & lines2
        
        return {
            'added': list(added),
            'removed': list(removed),
            'unchanged_count': len(unchanged),
            'total_changes': len(added) + len(removed)
        }
    
    def cleanup_old_backups(self, hostname: str = None, keep_count: int = 10):
        """
        Remove old backups, keeping only the most recent ones.
        
        Args:
            hostname: Optional hostname to clean up (None for all)
            keep_count: Number of backups to keep
        """
        if hostname:
            pattern = f"{hostname}_*.cfg"
        else:
            pattern = "*.cfg"
        
        backups = sorted(self.backup_dir.glob(pattern), reverse=True)
        
        # Delete old backups
        for backup in backups[keep_count:]:
            backup.unlink()
            logger.info(f"Deleted old backup: {backup}")
    
    def export_backup(self, backup_path: str, export_path: str):
        """
        Export a backup to a different location.
        
        Args:
            backup_path: Source backup path
            export_path: Destination path
        """
        import shutil
        shutil.copy2(backup_path, export_path)
        logger.info(f"Backup exported to: {export_path}")
